# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - foundwell-doc

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_210145041a054e0ca96a8d5e007b21d8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e5c968a15edf449095b31874039e8be9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_210145041a054e0ca96a8d5e007b21d8 }}/foundwell-core:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'foundwell-doc'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f15d85b236ca4b519d8ff91d1bdead42 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_210145041a054e0ca96a8d5e007b21d8 }}/foundwell-core:${{ github.sha }}'